# Generated by Django 5.0.6 on 2024-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_exchangerate_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_code', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_link', models.URLField()),
                ('price_in_dirhams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
            ],
        ),
    ]
