# Generated by Django 5.0.6 on 2024-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='address',
            new_name='address_detail',
        ),
        migrations.AddField(
            model_name='product',
            name='address_city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='address_province',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(),
        ),
    ]
