# Generated by Django 5.0.6 on 2024-07-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_rename_address_product_address_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('address_detail', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address_detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address_province',
        ),
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='price.address'),
            preserve_default=False,
        ),
    ]
