# Generated by Django 5.0.6 on 2024-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_address_remove_product_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
