# Generated by Django 4.2.14 on 2024-08-18 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_product_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
