# Generated by Django 4.2.7 on 2024-09-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_exchangerate_per_kg_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='per_kg_cost',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='profit_percentage',
        ),
    ]
