# Generated by Django 4.2.7 on 2024-09-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0013_remove_exchangerate_per_kg_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='per_kg_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5),
        ),
    ]
