# Generated by Django 4.2.7 on 2024-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
