# Generated by Django 4.2.7 on 2024-07-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_alter_scrapedata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
