# Generated by Django 4.2.7 on 2024-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_alter_scrapedata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedata',
            name='available',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
    ]
